### ISSUE TITLE
add PRs to automation for core triage project

### ISSUE THREAD

**Issue by lostmygithubaccount** [dbt-labs/actions#31]
the code looks like it's adding PRs, but doesn't seem to be. confirmed with this one: https://github.com/dbt-labs/dbt-bigquery/pull/284

which is still not showing up here: https://github.com/orgs/dbt-labs/projects/22/views/20

I vaguely recall PRs not working for some reason

**Comment by lostmygithubaccount** [comment]
ah...just for context in case someone takes this instead of me, there's some incorrect logic in the code here: 

https://github.com/dbt-labs/actions/blob/067b10a38b963237078bdd572da44a1dbdf56b1b/scripts/core-triage/project.py#L188-L193

then in that function:

https://github.com/dbt-labs/actions/blob/067b10a38b963237078bdd572da44a1dbdf56b1b/scripts/core-triage/project.py#L122-L131

so it's using the issues_query instead of a pr_query. when working on this the local script I was running and the one in here diverged a bit. I remember trying to change this over locally, running into some issues, and just removing the PR logic. might be a simple fix for this

**Comment by lostmygithubaccount** [comment]
the issue with naively re-using the issue code is this:

```
Processing PR label: ready_for_review...

200
{"errors":[{"path":["query","repository","pullRequests","filterBy"],"extensions":{"code":"argumentNotAccepted","name":"pullRequests","typeName":"Field","argumentName":"filterBy"},"locations":[{"line":4,"column":47}],"message":"Field 'pullRequests' doesn't accept argument 'filterBy'"}]}
Traceback (most recent call last):
  File "/workspaces/codyspace/actions/scripts/core-triage/project.py", line 221, in <module>
    main(PROJECT_NUM, CORE_TEAM, ISSUE_LABELS, PR_LABELS, NUM_ITEMS)
  File "/workspaces/codyspace/actions/scripts/core-triage/project.py", line 214, in main
    prs = get_prs(repo, pr_label, num_items)
  File "/workspaces/codyspace/actions/scripts/core-triage/project.py", line 143, in get_prs
    prs = process_request(
KeyError: 'data'
```

see the start of `prs_query`:

```python
# graphql query to get list of prs for the github repo
prs_query = """
    query {
        repository(owner:$org, name:$repo) {
            pullRequests(last:$num_items states:OPEN filterBy: {
                labels: [$label]
            }) {
                edges {
                    node {
...
```

removing the label works. can't find good info online for why `filterBy` isn't supported for prs.
